qb_stimulus:
  channel: DAC2 # DAC1 # for scope check
  channel_config:
    vop: 40000 # Gain of the DAC
    mix_reconstruction: true # flase # for scope check # Set to falso for zero order hold (ZOH) reconstruction
    nco_frequency: 8.1589e+9      # 50e6 # for scope check
  pulses:
    R_x_180:
      data: hann
      scale: 0.69947
      ramp: 120e-9 # Both up and down ramps
      flat: 300e-9
      use_stretch: true


ro_stimulus:
  channel: DAC0
  channel_config:
    vop: 20000
    mix_reconstruction: true # true
    nco_frequency: 9.01990734e+9    # 8.9985e9 # 9.00057e9 # 20e6 # 8.9995e9 # 9.0004e9
  pulses:
    readout:
      data: hann
      scale: (2e-1, 0deg) #2e-1
      ramp: 120e-9
      flat: 800e-9 #1e-6
      use_stretch: true


ro_capture:
  channel: ADC0
  channel_config:
    nco_frequency: 9.01990734e+9    # 8.9985e9 # 9.00057e9 # 9.0004e9
  memories:
    readout_trace:
      length: 2.2e-6
      decimation: 4
      region: plddr
    readout_accumulated:
      length: 2.2e-6
      decimation: 0
      region: plddr

  windows:
    boxcar:
      data: 0.1
      offset: [0, 0]
    matched:
      data: 0.1
      offset: [-50, 2779]
